// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL2RvfUZ1eIxijAUPnl-ezFKMc3cCeTlE',
    appId: '1:339799794779:web:3c5c4ca755f091e9c04b7e',
    messagingSenderId: '339799794779',
    projectId: 'phonenumber-faff6',
    authDomain: 'phonenumber-faff6.firebaseapp.com',
    storageBucket: 'phonenumber-faff6.appspot.com',
    measurementId: 'G-7ENN7XEMJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SZKfVWHGy_chfL8dIOOU2jRaA4k1XHQ',
    appId: '1:339799794779:android:19ece476e02679d7c04b7e',
    messagingSenderId: '339799794779',
    projectId: 'phonenumber-faff6',
    storageBucket: 'phonenumber-faff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PBrnrDj8r-t5yfzOKc9CzbuARrWPfjg',
    appId: '1:339799794779:ios:b225d5bef757df37c04b7e',
    messagingSenderId: '339799794779',
    projectId: 'phonenumber-faff6',
    storageBucket: 'phonenumber-faff6.appspot.com',
    iosBundleId: 'com.example.schedularApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7PBrnrDj8r-t5yfzOKc9CzbuARrWPfjg',
    appId: '1:339799794779:ios:b225d5bef757df37c04b7e',
    messagingSenderId: '339799794779',
    projectId: 'phonenumber-faff6',
    storageBucket: 'phonenumber-faff6.appspot.com',
    iosBundleId: 'com.example.schedularApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL2RvfUZ1eIxijAUPnl-ezFKMc3cCeTlE',
    appId: '1:339799794779:web:dad3d94509b785f3c04b7e',
    messagingSenderId: '339799794779',
    projectId: 'phonenumber-faff6',
    authDomain: 'phonenumber-faff6.firebaseapp.com',
    storageBucket: 'phonenumber-faff6.appspot.com',
    measurementId: 'G-RKSFY7LJX4',
  );

}